from os.path import dirname, join

PROJECT_DIRECTORY_PATH = dirname(dirname(__file__))

DATA_DIRECTORY_PATH = join(PROJECT_DIRECTORY_PATH, 'data')

DEPENDENCIES_DIRECTORY_PATH = join(PROJECT_DIRECTORY_PATH, 'dependencies')

CODE_DIRECTORY_PATH = join(PROJECT_DIRECTORY_PATH, 'code')

OUTPUTS_DIRECTORY_PATH = join(PROJECT_DIRECTORY_PATH, 'outputs')

MEDIA_DIRECTORY_PATH = join(PROJECT_DIRECTORY_PATH, 'media')
